### ISSUE TITLE
Serial port is blocked and another library cannot use it

### ISSUE THREAD

**Issue by ZZerog** [quarkiverse/quarkus-jef#70]
Hi,

I try to use JEF for driving GPIO on rPi3B+ and GPIO working OK, but I have another lib for serial port comunication and 
when JEF start (calling first line of JEF lib) serial communication is blocked and another serial lib cannot use the serial port.

I tried setup someting as

```
quarkus.jef.serial.serial0.enabled=false 
quarkus.jef.serial.enabled=false
```

or as java argumet

`-Dquarkus.jef.serial.serial0.enabled=false `

or try to set true value, but nothing change.

Can you help me with this issues please :)

**Comment by alexeysharandin** [comment]
Hi! GPIO or Serial? It's two different type of API.

For GPIO you need to disable like here:
https://github.com/alexeysharandin/quarkus-jef-example/blob/main/src/main/resources/application.properties#L2-L3

**Comment by ZZerog** [comment]
OK,

I used GPIO as follow:

```
public static String GPIO_PATH = "/dev/gpiochip0";
GpioPin pin = GpioManager.getPin(GPIO_PATH, num);
pin.setDirection(GpioPin.Direction.OUTPUT);
pin.write(GpioPin.State.HIGH);
```

this part work greate as I expected but when (later in code) I try to use serial port (on different GPIO pins with different serial library), seril port is blocked.

I used GPIO6,  GPIO13,  GPIO19 and  GPIO26 as output and  GPIO12,  GPIO16,  GPIO20 and  GPIO21 as input. 
And UART0 tx and rx for serial (uart) mapped to /dev as serial0

```

pi@pi-:~$ ll /dev | grep serial
lrwxrwxrwx  1 root root           5 Jun 16 16:29 serial0 -> ttyS0
lrwxrwxrwx  1 root root           7 Jun 16 16:29 serial1 -> ttyAMA0
```

Serial lib. is here https://github.com/scream3r/java-simple-serial-connector (JSSC) and I using it for years on different linux machines. When Serial.writeBytes is called return false and DOC say: 

`@return If the operation is successfully completed, the method returns true, otherwise false `

and cpp (jni) code in JSSC look like this (importing linux/serial.h)

```
JNIEXPORT jboolean JNICALL Java_jssc_SerialNativeInterface_writeBytes
  (JNIEnv *env, jobject object, jlong portHandle, jbyteArray buffer){
    jbyte* jBuffer = env->GetByteArrayElements(buffer, JNI_FALSE);
    jint bufferSize = env->GetArrayLength(buffer);
    jint result = write(portHandle, jBuffer, (size_t)bufferSize);
    env->ReleaseByteArrayElements(buffer, jBuffer, 0);
    return result == bufferSize ? JNI_TRUE : JNI_FALSE;
}
```

Sorry I know that my english is somewhat confusing :-/

**Comment by alexeysharandin** [comment]
Hmmm....  If you not using Serial from JEF -> API for serial not initialized and not using /dev/serial*
In my example here: https://github.com/alexeysharandin/quarkus-jef-example I'm using serial + GPIO in parallel and everything works fine. In low level the code in JEF and in JSSC looks like the same... 
but again - if you don't use [this](https://github.com/quarkiverse/quarkus-jef/blob/main/linux-core/src/main/java/io/quarkiverse/jef/java/embedded/framework/linux/serial/SerialPort.java) in your code - JEF not opening port

**Comment by ZZerog** [comment]
Hmm ...yes, you are right.

I did a minimal plain project only with JEF (GPIO) and JSSC (UART) and work well.
So I must looking for problem I my own code. Sorry for that and thansk for your time!

Here is test program which working fine!

```
public class GpioTest {

    final static int baudrate = 57600;
    final static String GPIO_PATH = "/dev/gpiochip0";
    final int gpioPin = 26;


    public void test() {
        try {


            SerialPort serialPort = new SerialPort("/dev/serial0");
            serialPort.openPort();
            
            serialPort.setParams(baudrate,
                    SerialPort.DATABITS_8,
                    SerialPort.STOPBITS_1,
                    SerialPort.PARITY_NONE);

            //serial port access A
            for (int i = 0; i < 10; i++) {
                System.out.println("Writing to serial port 1B, result = "+serialPort.writeBytes("a".getBytes()));
            }


            GpioPin pin = GpioManager.getPin(GPIO_PATH, gpioPin);
            pin.setDirection(GpioPin.Direction.OUTPUT);
            pin.write(GpioPin.State.HIGH); //default state == OFF

            int i = 0;
            while(i < 5) {
                i++;
                pin.write(i%2==0?GpioPin.State.HIGH:GpioPin.State.LOW);
                Thread.sleep(300);
            }

            //serial port access B
            for (i = 0; i < 10; i++) {
                System.out.println("Writing to serial port 1B, result = "+serialPort.writeBytes("b".getBytes()));
            }

            System.out.println("Exiting");
            System.exit(0);

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}

```

**Comment by alexeysharandin** [comment]
Fine!
BTW: I recommend to use Quarkus + Jef. In this case you can use all Quarkus features (http, amazon, jpa and more and more) and build 100M native executable images instead of using JDK and jars.
